---
- hosts: guests:extras
#- hosts: extras
  become: yes
  become_user: isucon
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
    # ruby
    - command: /home/isucon/.xbuild/ruby-install 2.7.3 /home/isucon/.local/ruby
      args:
        creates: /home/isucon/.local/ruby/bin/ruby
    - command: /.local/ruby/bin/gem install bundler
      args:
        creates: /home/isucon/.local/ruby/bin/bundle
    # node
    - command: /home/isucon/.xbuild/node-install v4.4.3 /home/isucon/.local/node
      args:
        creates: /home/isucon/.local/node/bin/node
      tags:
        - nodejs
    # golang
    - command: /home/isucon/.xbuild/go-install 1.16.4 /home/isucon/.local/go
      args:
        creates: /home/isucon/.local/go/bin/go

- hosts: guests:extras
  become: yes
  gather_facts: no
  tasks:
    - name: Apt update
      apt: update_cache=yes
      tags: php7
    - name: PHP7 install
      apt: name="{{item}}"
      with_items:
        - php7.4-cli
        - php7.4-fpm
        - php7.4-mysql
        - php-memcached
      tags: php7
    - name: copy www.conf (php-fpm)
      copy: src=../files/etc/php/7.4/fpm/pool.d/www.conf dest=/etc/php/7.4/fpm/pool.d/www.conf owner=root mode=644
    - name: stop php-fpm
      service: name=php7.4-fpm state=stopped enabled=no
# install java8 and sbt
- hosts: guests:extras
  become: yes
  gather_facts: no
  tasks:
    - name: Apt add bintray and jessie-backports
      apt_repository: repo="{{item}}"
      with_items:
        - deb http://http.debian.net/debian jessie-backports main
        - deb https://dl.bintray.com/sbt/debian /
      tags: sbt
    - name: Apt add key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823
      tags: sbt
    - name: Install jre
      apt:
        update_cache: yes
        default_release: jessie-backports
        name: "{{item}}"
      with_items:
        - openjdk-8-jre-headless
        - ca-certificates-java
      tags: sbt
    - name: Install jdk and sbt
      apt: name="{{item}}"
      with_items:
        - openjdk-8-jdk
        - sbt
      tags: sbt